version: '2'

services:

    hub:
        image: selenium/hub
        volumes:
            - /dev/shm:/dev/shm
            - /etc/localtime:/etc/localtime:ro
        ports:
              - "4444:4444"

    chrome:
        image: selenium/node-chrome-debug
        depends_on:
            - hub
        links:
            - hub
        env_file:
            - ../.env
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
            - HUB_PORT_4444_TCP_PORT=4444
            - CHROME=true
        volumes_from:
            - hub

    novnc:
        build:
            context: ./
            dockerfile: novnc.dockerfile
        command: chrome
        depends_on:
            - chrome
        ports:
            - 6080:6080
        environment:
            - VNC_PASSWORD=

    console:
        build:
            args:
                GID: ${_GID}
                UID: ${_UID}
                USER: ${USER}
                LOCAL_IP_TESTE: ${_LOCAL_IP_TESTE}
                LOCAL_PORT_TESTE: ${_LOCAL_PORT_TESTE}
            context: ./
            dockerfile: console.dockerfile
        depends_on:
            - novnc
        ports:
            - 9001:9000
        stdin_open: true
        tty: true
        volumes:
            - ..:/src
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/.gitconfig:${HOME}/.gitconfig
            - ${HOME}/.git-credentials:${HOME}/.git-credentials
            - ../.local/.bash_history:${HOME}/.bash_history
        working_dir: /src